version: '3.8'

services:
  postgres:
    image: postgres:15 
    container_name: account-service-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Welcome@123
      POSTGRES_DB: account-service-db
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
