# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/account-service-db
    username: root
    password: Welcome@123
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      enabled: false