spring:
    profiles:
      active:
        - dev
    application:
        name: account-service
    cloud:
        consul:
            host: localhost
            port: 8500 
    flyway:
      baseline-on-migrate: true        

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled:  true                        
keycloak:
  auth-server-url: http://localhost:8080
  master-realm: master
  admin-client-id: admin-cli
  admin-client-secret: change-me
  admin-username: admin
  admin-password: admin
 