# application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-host}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
